Fix nil error panic
gopasspw/gopass pull request #1604
Opened 2020-09-29 20:00 UTC by Feresey

Fixes panic on incorrect number

```text
❯ gopass new
[ 0] Website Login
[ 1] PIN Code (numerical)
[ 2] Generic

Please select the type of secret you would like to create [0]: 123
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x5557dc575be5]

goroutine 1 [running]:
github.com/gopasspw/gopass/internal/cui.GetSelection(0x5557dd1e6ae0, 0xc000afa390, 0x5557dcb335c8, 0x39, 0xc000afae10, 0x3, 0x3, 0x3, 0x5557dd10fe00, 0x5557dd151160)
	github.com/gopasspw/gopass/internal/cui/cui.go:31 +0x245
github.com/gopasspw/gopass/internal/action/create.Create(0xc000098880, 0x5557dd1e38a0, 0xc00000e140, 0x0, 0x0)
	github.com/gopasspw/gopass/internal/action/create/create.go:53 +0x233
github.com/gopasspw/gopass/internal/action/create.GetCommands.func1(0xc000098880, 0x0, 0x0)
	github.com/gopasspw/gopass/internal/action/create/commands.go:22 +0x3f
github.com/urfave/cli/v2.(*Command).Run(0xc00038a240, 0xc000098600, 0x0, 0x0)
	github.com/urfave/cli/v2@v2.2.0/command.go:164 +0x4ed
github.com/urfave/cli/v2.(*App).RunContext(0xc000102d80, 0x5557dd1e6ae0, 0xc000afa390, 0xc00000e080, 0x2, 0x2, 0x0, 0x0)
	github.com/urfave/cli/v2@v2.2.0/app.go:306 +0x830
main.main()
	github.com/gopasspw/gopass/main.go:95 +0x474
```

2020-09-30 00:04 UTC, AnomalRoil requested changes
Ah, good catch! Thanks for the fix.

Please just add a RELEASE_NOTE in your commit so that it'll work with our CI :D 
Just something like:
`RELEASE_NOTES=[BUGFIX] Nil dereference in cui`

2020-09-30 19:51 UTC, dominikschulz submitted a review, later dismissed
LGTM. Thanks!

2020-10-01 10:02 UTC, AnomalRoil approved these changes

2020-10-01 17:55 UTC, dominikschulz approved these changes
LGTM. Thanks!

2020-10-01 17:55 UTC, merged