Add support for inserting secrets with colons in the name
gopasspw/gopass pull request #1610
Opened 2020-10-03 17:11 UTC by lsowen

Fixes #1609 

Signed-off-by: lsowen <logan@s1network.com>

2020-10-03 18:14 UTC, dominikschulz requested changes
Thank you very much!

Two minor nits, otherwise good.

2020-10-03 18:14 UTC, dominikschulz commented on CHANGELOG.md
> +[BUGFIX] Allow secret names to have a colon in the name
Thank you for remembering to add this to the changelog.

In the past we didn't enforce this so we have a CommitCheck that looks for a RELEASE_NOTES= entry.

Could you please add `RELEASE_NOTES=[BUGFIX] Allow secret names to have a colon in the name` to the commit message so we can automatically parse that when we create the next release?

2020-10-03 18:14 UTC, dominikschulz commented on internal/action/clihelper.go
> +	if(c.Args().Len() == 1) {
This deserves a short comment.

2020-10-03 18:56 UTC, dominikschulz approved these changes
LGTM. Thank you!

2020-10-03 18:58 UTC, dominikschulz commented
You have an extra set of brackets where Go doesn't want them.
If you remove those this should be good to merge.

2020-10-03 20:14 UTC, lsowen commented
Too much java, and not enough golang lately :grin:

2020-10-04 08:02 UTC, dominikschulz approved these changes
LGTM

2020-10-04 08:02 UTC, merged