doc: summon.md: we now need gopass-summon-provider
gopasspw/gopass pull request #1658
Opened 2020-11-22 19:05 UTC by marco-m

RELEASE_NOTES=n/a

Signed-off-by: Marco Molteni <marco.molteni@mailbox.org>

2020-11-22 19:29 UTC, marco-m commented
This closes #1633

2020-11-23 13:57 UTC, AnomalRoil requested changes
Also, if you are using Summon yourself, maybe you explain why it's interesting to use with Gopass? 
For example: will Summon erase the env var after usage or not?

2020-11-23 13:57 UTC, AnomalRoil commented on docs/summon-provider.md
> +The gopass repository contains the [cmd/gopass-summon-provider](https://github.com/gopasspw/gopass/tree/master/cmd/gopass-summon-provider) tool, that can be used as [summon provider](https://cyberark
Please use the [github relative links](https://github.blog/2013-01-31-relative-links-in-markup-files/) here.

2020-12-02 13:49 UTC, dominikschulz submitted a review, later dismissed
LGTM. Thanks.

But please use relative links.

2020-12-02 15:20 UTC, marco-m commented
Ah, it looks like that a force push dismisses reviews in this repo?
In any case, I updated the commit to use relative links.

> Also, if you are using Summon yourself, maybe you could explain why it's interesting to use with Gopass? I don't know anything about Summon myself, I think it could help users to have a clearer understanding of what is Summon and why it's nice to use with Gopass.

Maybe another time.

> For example: will Summon erase the env var after usage or not?

It would be impossible for summon to leave around the environment variables actually, due to how shells and subprocesses work.

In general, summon is well though-out from a security point of view.

2020-12-03 10:52 UTC, dominikschulz approved these changes
LGTM

2020-12-03 10:52 UTC, merged