[cleanup] Remove Deprecated math/rand.Seed Usage
gopasspw/gopass pull request #2675
Opened 2023-10-03 11:46 UTC by orangekame3

## Description
This commit removes the use of the deprecated math/rand.Seed method.

## Checked

▼make test 

```shell
gopass [ fix/issue-2650][🐹 v1.21.0]
❯ make test
>> BUILD, version = 1.15.8/ecf31ca3, output = gopass [OK]
>> TEST, "fast-mode": race detector off
     ok  	github.com/gopasspw/gopass	0.050s
     ?   	github.com/gopasspw/gopass/helpers/changelog	[no test files]
     ?   	github.com/gopasspw/gopass/helpers/man	[no test files]
     ?   	github.com/gopasspw/gopass/helpers/msipkg	[no test files]
     ?   	github.com/gopasspw/gopass/helpers/postrel	[no test files]
     ?   	github.com/gopasspw/gopass/helpers/release	[no test files]
     ok  	github.com/gopasspw/gopass/internal/action	3.087s
     ok  	github.com/gopasspw/gopass/internal/action/exit	0.001s
     ok  	github.com/gopasspw/gopass/internal/action/pwgen	0.004s
     ok  	github.com/gopasspw/gopass/internal/audit	0.028s
     ok  	github.com/gopasspw/gopass/internal/backend	0.038s
     ?   	github.com/gopasspw/gopass/internal/backend/crypto	[no test files]
     ok  	github.com/gopasspw/gopass/internal/backend/crypto/age	0.029s
     ok  	github.com/gopasspw/gopass/internal/backend/crypto/gpg	0.001s
     ok  	github.com/gopasspw/gopass/internal/backend/crypto/gpg/cli	0.012s
     ok  	github.com/gopasspw/gopass/internal/backend/crypto/gpg/colons	0.001s
     ok  	github.com/gopasspw/gopass/internal/backend/crypto/gpg/gpgconf	0.001s
     ok  	github.com/gopasspw/gopass/internal/backend/crypto/plain	0.001s
     ?   	github.com/gopasspw/gopass/internal/backend/storage	[no test files]
     ?   	github.com/gopasspw/gopass/internal/backend/storage/fossilfs	[no test files]
     ok  	github.com/gopasspw/gopass/internal/backend/storage/fs	0.251s
     ok  	github.com/gopasspw/gopass/internal/backend/storage/gitfs	0.037s
     ok  	github.com/gopasspw/gopass/internal/cache	1.102s
     ?   	github.com/gopasspw/gopass/internal/cache/ghssh	[no test files]
     ok  	github.com/gopasspw/gopass/internal/completion/fish	0.002s
     ok  	github.com/gopasspw/gopass/internal/completion/zsh	0.002s
     ok  	github.com/gopasspw/gopass/internal/config	0.037s
     ok  	github.com/gopasspw/gopass/internal/config/legacy	0.031s
     ok  	github.com/gopasspw/gopass/internal/create	0.030s
     ok  	github.com/gopasspw/gopass/internal/cui	0.003s
     ok  	github.com/gopasspw/gopass/internal/diff	0.001s
     ok  	github.com/gopasspw/gopass/internal/editor	0.004s
     ?   	github.com/gopasspw/gopass/internal/env	[no test files]
     ?   	github.com/gopasspw/gopass/internal/hashsum	[no test files]
     ?   	github.com/gopasspw/gopass/internal/hook	[no test files]
     ok  	github.com/gopasspw/gopass/internal/notify	0.001s
     ok  	github.com/gopasspw/gopass/internal/out	0.001s
     ok  	github.com/gopasspw/gopass/internal/pwschemes/argon2i	0.468s
     ok  	github.com/gopasspw/gopass/internal/pwschemes/argon2id	0.731s
     ok  	github.com/gopasspw/gopass/internal/pwschemes/bcrypt	0.376s
     ?   	github.com/gopasspw/gopass/internal/queue	[no test files]
     ok  	github.com/gopasspw/gopass/internal/recipients	0.001s
     ?   	github.com/gopasspw/gopass/internal/reminder	[no test files]
     ok  	github.com/gopasspw/gopass/internal/set	0.001s
     ok  	github.com/gopasspw/gopass/internal/store	0.001s
     ok  	github.com/gopasspw/gopass/internal/store/leaf	2.847s
     ?   	github.com/gopasspw/gopass/internal/store/mockstore	[no test files]
     ?   	github.com/gopasspw/gopass/internal/store/mockstore/inmem	[no test files]
     ok  	github.com/gopasspw/gopass/internal/store/root	0.036s
     ok  	github.com/gopasspw/gopass/internal/tpl	0.846s
     ok  	github.com/gopasspw/gopass/internal/tree	0.001s
     ok  	github.com/gopasspw/gopass/internal/updater	0.003s
     ok  	github.com/gopasspw/gopass/pkg/appdir	0.002s
     ok  	github.com/gopasspw/gopass/pkg/clipboard	0.377s
     ok  	github.com/gopasspw/gopass/pkg/ctxutil	0.003s
     ok  	github.com/gopasspw/gopass/pkg/debug	0.001s
     ok  	github.com/gopasspw/gopass/pkg/fsutil	0.234s
     ok  	github.com/gopasspw/gopass/pkg/gitconfig	0.002s
     ?   	github.com/gopasspw/gopass/pkg/gopass	[no test files]
     ok  	github.com/gopasspw/gopass/pkg/gopass/api	0.029s
     ?   	github.com/gopasspw/gopass/pkg/gopass/apimock	[no test files]
     ok  	github.com/gopasspw/gopass/pkg/gopass/secrets	0.026s
     ok  	github.com/gopasspw/gopass/pkg/gopass/secrets/secparse	0.001s
     ok  	github.com/gopasspw/gopass/pkg/otp	0.005s
     ?   	github.com/gopasspw/gopass/pkg/pinentry/cli	[no test files]
     ok  	github.com/gopasspw/gopass/pkg/protect	0.001s
     ok  	github.com/gopasspw/gopass/pkg/pwgen	0.015s
     ok  	github.com/gopasspw/gopass/pkg/pwgen/pwrules	0.002s
     ok  	github.com/gopasspw/gopass/pkg/pwgen/xkcdgen	0.001s
     ok  	github.com/gopasspw/gopass/pkg/qrcon	0.001s
     ok  	github.com/gopasspw/gopass/pkg/tempfile	0.001s
     ok  	github.com/gopasspw/gopass/pkg/termio	0.002s
```

2023-10-04 11:49 UTC, orangekame3 commented
checked ⤵
```
gopass [ fix/issue-2650][🐹 v1.21.0][⏱ 2s]
❯ golangci-lint run
```

2023-10-30 20:08 UTC, AnomalRoil requested changes
Just a few comments

2023-10-30 20:08 UTC, AnomalRoil commented on pkg/pwgen/pwgen_test.go
> +	"math/rand"
This means now the whole file is using `math/rand` instead of `crypto/rand` when it's calling `rand`, that's a bad idea.

2023-10-30 20:08 UTC, AnomalRoil commented on pkg/pwgen/pwgen_test.go
> +	gr = rand.New(rand.NewSource(1789))
Hence the global variable. I understand better why you need one below, but really its name should be more explicit.

2024-03-30 08:25 UTC, closed without merging

2024-03-30 08:25 UTC, dominikschulz commented
Due to the lack of activity I assume the author lost interest in this PR. As we can't merge it as-is I'm closing it.

Feel free to re-open once you have addressed the open comments.